import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'
const Layout = dynamic(() => import('../components/Layout'))
const Report = dynamic(()=> import('../components/campaign/Report'))
const Result = dynamic(()=> import('../components/campaign/Result'))
const Number = dynamic(()=> import('../components/campaign/Number'))


const Home: NextPage = () => {
  return (
    <>
    <Layout>
      <Head>
        <title>TBS Campaign Insight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Prompt:wght@200;300;400;500;600;700;800&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Sarabun:wght@300;400;500;600;700;800&display=swap"
        />
      </Head>
      <Report/>
      <Result/>
      <Number/>
    </Layout>
    </>
  )
}

export default Home;
